_wandb:
    value:
        cli_version: 0.19.8
        m: []
        python_version: 3.11.5
        t:
            "1":
                - 2
                - 3
                - 5
                - 53
                - 55
            "2":
                - 2
                - 3
                - 5
                - 53
                - 55
            "3":
                - 2
                - 3
                - 8
                - 13
                - 16
                - 23
                - 55
                - 62
            "4": 3.11.5
            "5": 0.19.8
            "8":
                - 5
            "10":
                - 9
                - 17
            "12": 0.19.8
            "13": darwin-arm64
batch_size:
    value: 32
epochs:
    value: 20
hidden_units:
    value: 50
loss_function:
    value: mean_squared_error
optimizer:
    value: adam
time_steps:
    value: 50
